# Offense count: 2
Lint/UselessAssignment:
  Exclude:
    - 'app/controllers/books_controller.rb'
    - 'spec/model/book_spec.rb'

# Offense count: 2
Metrics/AbcSize:
  Max: 39

# Offense count: 3
# Configuration parameters: CountComments, ExcludedMethods.
# ExcludedMethods: refine
Metrics/BlockLength:
  Max: 32

# Offense count: 2
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/MethodLength:
  Max: 17

# Offense count: 1
# Configuration parameters: EnforcedStyle, IgnoredPatterns.
# SupportedStyles: snake_case, camelCase
Naming/MethodName:
  Exclude:
    - 'app/controllers/books_controller.rb'

# Offense count: 1
# Configuration parameters: EnforcedStyle.
# SupportedStyles: snake_case, camelCase
Naming/VariableName:
  Exclude:
    - 'app/controllers/books_controller.rb'

# Offense count: 15
# Configuration parameters: AllowedChars.
Style/AsciiComments:
  Exclude:
    - 'config/deploy.rb'
    - 'config/unicorn.rb'

# Offense count: 2
Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/controllers/registers_controller.rb'
